package org.altadoon.gt6x.common.recipe;

import gregapi.data.RM;
import gregapi.recipes.Recipe;

public class RB {
	public static final RB DidYouKnow=new RB(RM.DidYouKnow)
			,  Autocrafter=new RB(RM.Autocrafter)
			,  DistillationTower=new RB(RM.DistillationTower)
			,  CryoDistillationTower=new RB(RM.CryoDistillationTower)
			,  SteamCracking=new RB(RM.SteamCracking)
			,  CatalyticCracking=new RB(RM.CatalyticCracking)
			,  Fermenter=new RB(RM.Fermenter)
			,  Distillery=new RB(RM.Distillery)
			,  Drying=new RB(RM.Drying)
			,  Coagulator=new RB(RM.Coagulator)
			,  CrystallisationCrucible=new RB(RM.CrystallisationCrucible)
			,  Mixer=new RB(RM.Mixer)
			,  HeatMixer=new RB(RM.HeatMixer)
			,  BurnMixer=new RB(RM.BurnMixer)
			,  CryoMixer=new RB(RM.CryoMixer)
			,  CokeOven=new RB(RM.CokeOven)
			,  Roasting=new RB(RM.Roasting)
			,  Bath=new RB(RM.Bath)
			,  Sluice=new RB(RM.Sluice)
			,  MagneticSeparator=new RB(RM.MagneticSeparator)
			,  Sifting=new RB(RM.Sifting)
			,  Calciner=new RB(RM.Calciner)
			,  ImplosionCompressor=new RB(RM.ImplosionCompressor)
			,  Compressor=new RB(RM.Compressor)
			,  Injector=new RB(RM.Injector)
			,  Loom=new RB(RM.Loom)
			,  Laminator=new RB(RM.Laminator)
			,  Autoclave=new RB(RM.Autoclave)
			,  Freezer=new RB(RM.Freezer)
			,  Polarizer=new RB(RM.Polarizer)
			,  Lightning=new RB(RM.Lightning)
			,  Slicer=new RB(RM.Slicer)
			,  Lathe=new RB(RM.Lathe)
			,  Debarker=new RB(RM.Debarker)
			,  Press=new RB(RM.Press)
			,  Squeezer=new RB(RM.Squeezer)
			,  Juicer=new RB(RM.Juicer)
			,  Furnace=new RB(RM.Furnace)
			,  Microwave=new RB(RM.Microwave)
			,  Cooking=new RB(RM.Cooking)
			,  BumbleQueens=new RB(RM.BumbleQueens)
			,  Bumblelyzer=new RB(RM.Bumblelyzer)
			,  Trees=new RB(RM.Trees)
			,  Plantalyzer=new RB(RM.Plantalyzer)
			,  Wiremill=new RB(RM.Wiremill)
			,  ClusterMill=new RB(RM.ClusterMill)
			,  RollingMill=new RB(RM.RollingMill)
			,  RollBender=new RB(RM.RollBender)
			,  RollFormer=new RB(RM.RollFormer)
			,  LaserEngraver=new RB(RM.LaserEngraver)
			,  Welder=new RB(RM.Welder)
			,  Anvil=new RB(RM.Anvil)
			,  AnvilBendSmall=new RB(RM.AnvilBendSmall)
			,  AnvilBendBig=new RB(RM.AnvilBendBig)
			,  Centrifuge=new RB(RM.Centrifuge)
			,  Electrolyzer=new RB(RM.Electrolyzer)
			,  ToolHeads=new RB(RM.ToolHeads)
			,  Sharpening=new RB(RM.Sharpening)
			,  CrucibleAlloying=new RB(RM.CrucibleAlloying)
			,  CrucibleSmelting=new RB(RM.CrucibleSmelting)
			,  Cutter=new RB(RM.Cutter)
			,  Smelter=new RB(RM.Smelter)
			,  Mortar=new RB(RM.Mortar)
			,  Shredder=new RB(RM.Shredder)
			,  Crusher=new RB(RM.Crusher)
			,  Extruder=new RB(RM.Extruder)
			,  Hammer=new RB(RM.Hammer)
			,  Chisel=new RB(RM.Chisel)
			,  Nanofab=new RB(RM.Nanofab)
			,  Printer=new RB(RM.Printer)
			,  ScannerVisuals=new RB(RM.ScannerVisuals)
			,  ScannerMolecular=new RB(RM.ScannerMolecular)
			,  Massfab=new RB(RM.Massfab)
			,  Replicator=new RB(RM.Replicator)
			,  Fusion=new RB(RM.Fusion)
			,  Canner=new RB(RM.Canner)
			,  Boxinator=new RB(RM.Boxinator)
			,  Unboxinator=new RB(RM.Unboxinator)
			,  Generifier=new RB(RM.Generifier)
			,  BedrockOreList=new RB(RM.BedrockOreList)
			,  ByProductList=new RB(RM.ByProductList)
			,  BlastFurnace=new RB(RM.BlastFurnace)
			,  VacuumFreezer=new RB(RM.VacuumFreezer)
			,  Assembler=new RB(RM.Assembler)
			,  CNC=new RB(RM.CNC);

				public final Recipe.RecipeMap MAP;
	RB(Recipe.RecipeMap aRecipeMap){
		MAP = aRecipeMap;
	}

	public RecipeBuilder builder(){
		return new RecipeBuilder(MAP);
	}
}
